kind: pipeline
name: default

steps:
  - name: setup
    image: node:carbon
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn

  - name: build
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn build:prod

  - name: test
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn test

  - name: compile-typescript
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn run tsc

  - name: lint-typescript
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-ts

  - name: lint-less
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-less

  - name: lint-prettier
    image: node:carbon
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn lint-prettier

  - name: release
    image: plugins/docker
    secrets:
      - docker_username
      - docker_password
      - owf_sentry_dsn
      - ow4_address
      - ow4_sso_callback
      - ow4_sso_client_id
      - owf_sentry_dsn
      - owf_google_analytics_keys
      - owf_vapid_public_key
      - owf_webpush_server_url
    when:
      event: tag
      status: success
    repo: registry.online.ntnu.no/dotkom/onlineweb-frontend
    registry: registry.online.ntnu.no
    dockerfile: Dockerfile.prod
    build_args_from_env:
      - owf_sentry_dsn
      - ow4_address
      - ow4_sso_callback
      - ow4_sso_client_id
      - owf_sentry_dsn
      - owf_google_analytics_keys
      - owf_vapid_public_key
      - owf_webpush_server_url
    tags:
      - "${DRONE_TAG}"
      - latest

  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    when:
      event: push
      branch: master
      status: success
    settings:
      host: nansen.online.ntnu.no
      port: 22
      username: root
      key:
        from_secret: ssh_key
      command_timeout: 600s
      script:
        - /srv/www/owf-staging/deploy.sh

